### ISSUE TITLE
Authentification: REST

### ISSUE THREAD

**Issue by purrplingcat** [Caloriosa/core#7]
Create CRUD and REST interface for authentification `/auth` and `/auth/identity`

**Source requirement:** 
- https://gist.github.com/EllenFawkes/921c2766b17eff1e4e9b7df72a553bd0#file-05_auth-md -
- https://gist.github.com/EllenFawkes/921c2766b17eff1e4e9b7df72a553bd0#auth

**Comment by CallMeFoxie** [comment]
Done.
