### ISSUE TITLE
Users: Datamodel

### ISSUE THREAD

**Issue by purrplingcat** [Caloriosa/core#8]
Create a datamodel for users

**Requirement source:**
- https://gist.github.com/EllenFawkes/921c2766b17eff1e4e9b7df72a553bd0#file-05_auth-md
- https://gist.github.com/EllenFawkes/921c2766b17eff1e4e9b7df72a553bd0#users
- Caloriosa/caloriosa#7

**Comment by CallMeFoxie** [comment]
Done
